### PR TITLE
v4

### PR DESCRIPTION
**Pull request by chimosky**
@JuiP @quozl kindly review.

### CODE REVIEW

**Review by JuiP — APPROVED** [review]
Before the release, I might as well add hi and mr translations. Working on it, will be done by tonight!
Edit: It's taking more time than I thought, I have completed half the words, will complete it tomorrow.

**Comment by chimosky** [comment]
>  Edit: It's taking more time than I thought, I have completed half the words, will complete it tomorrow.

I'll leave it open until tomorrow.

**Comment by JuiP** [comment]
Done in b7e1e18 , could you please review and cherry-pick the commit? :)

**Comment by srevinsaju** [comment]
Please pause this merge, there are many problems in this version right now; 
The same problems as that of iKnowIndia (DBusLookupError and some other errors)
```
Cannot load stats invalid literal for int() with base 10: '0.08333333333333333'
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sugar3/activity/activity.py", line 1336, in close
    self._do_close(skip_save)
  File "/usr/lib/python3.8/site-packages/sugar3/activity/activity.py", line 1310, in _do_close
    self._complete_close()
  File "/usr/lib/python3.8/site-packages/sugar3/activity/activity.py", line 1297, in _complete_close
    dbus.service.Object.remove_from_connection(self._bus)
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 629, in remove_from_connection
    raise LookupError('%r is not exported at a location matching '
LookupError: <sugar3.activity.activityservice.ActivityService at /org/laptop/Activity/9e1f299ef0a032053408923cf21f747dd14effd2 at 0x7f0490052730> is not exported at a location matching (None,None)
```

**Comment by chimosky** [comment]
Can you share how to reproduce? And did you test at master or at e911f07 or at  b7e1e18?

**Comment by srevinsaju** [comment]
@chimosky 

This might not be directly reproducible because of some code which should not be added in the first 
place
* `conzoco.py` uses `sys.exit()` to kill the process. All the errors, like saving the configuration files and `LookupError` is suppressed by `sys.exit()`. If you replace `sys.exit` with Sugar toolkit's builtin exit option; you can reproduce the errors
* Ctrl-Q Does not terminate the activity, indicating there is something wrong in the exit of the conzoco file. I will address and fix this issue in #5. 
* The python port was incomplete because it did not take care of the floor division while writing the data files. This write_file had not been implemented in the activity.py in the first place and hence the statistics were not written

To check something which has been going wrong with `conzoco` activities; see https://github.com/sugarlabs/iknowIndia/pull/7#issuecomment-579263930

Unfortunately, the `conzoco.py` has diverged very much; making maintenance a bit hard

**Comment by chimosky** [comment]
I was able to reproduce this error by pressing `Ctrl+Q` while in the activity.

```
Cannot load stats invalid literal for int() with base 10: '0.0'
```

I was following https://github.com/sugarlabs/iknowIndia/pull/7#issuecomment-579263930.

I'll wait for your fixes.

**Comment by srevinsaju** [comment]
@chimosky I guess I am done on #5 ; The code was already badly formatted; Would you like me to run a linting tool on this conzoco.py? 
Please test it; I am not sure if I replicated all the fixes as in `iknowIndia`; 
A coverage test might be useful. 

New features on #5:
* Add a toolbar and working Stop button

Bugfixes on #5:
* Fix LookupError
* Fix writing of stats

@JuiP @quozl please review #5 before merge

**Comment by chimosky** [comment]
Thanks @JuiP @srevinsaju for your work.

**Comment by srevinsaju** [comment]
No problem @chimosky :smile:

**Pull request merged**
